using Ambev.DeveloperEvaluation.Domain.Entities;
using Ambev.DeveloperEvaluation.Domain.Enums;

namespace Ambev.DeveloperEvaluation.Domain.Repositories;

public interface ISaleOrderRepository
{
    /// <summary>
    /// Retrieves a paginated list of sale orders
    /// </summary>
    /// <param name="page">The page number to retrieve (1-based)</param>
    /// <param name="amountPerPage">The number of orders per page</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>A tuple containing the total number of pages and the list of orders</returns>
    Task<(int totalPages, IEnumerable<SaleOrder> orders)> GetOrders(
        int page,
        int amountPerPage,
        bool includeProductList = true,
        int? orderNumberFrom = null,
        int? orderNumberTo = null,
        string? customerName = null,
        string? branchName = null,
        CancelStatus? cancelStatus = null,
        DateTime? dateFrom = null,
        DateTime? dateTo = null,
        string? orderBy = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a Sale Order by it's ID
    /// </summary>
    /// <param name="id">The sale order's id to find</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>The created sale order</returns>
    Task<SaleOrder?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Creates a new sale order in the repository
    /// </summary>
    /// <param name="order">The sale order to create</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>The created sale order</returns>
    Task<SaleOrder> CreateAsync(SaleOrder order, CancellationToken cancellationToken = default);
    Task<SaleOrder> UpdateAsync(SaleOrder order, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the last valid order's number persisted
    /// </summary>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>The last persisted order number</returns>
    [Obsolete("Deprecated: OrderNumber is generated by database sequence.")]
    Task<int> GetLastOrderNumber(CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a sale order from the repository.
    /// </summary>
    /// <param name="id">The unique identifier of the sale order to delete.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if the sale order was deleted, false if not found.</returns>
    Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default);
}
