using AutoMapper;
using MediatR;
using FluentValidation;
using Ambev.DeveloperEvaluation.Domain.Repositories;
using Ambev.DeveloperEvaluation.Domain.Entities;
using Ambev.DeveloperEvaluation.Domain.Events;
using Microsoft.Extensions.Logging;

namespace Ambev.DeveloperEvaluation.Application.SaleOrders.CreateSaleOrder;

/// <summary>
/// Handler for processing <see cref="CreateSaleOrderCommand"/> requests.
/// </summary>
public class CreateSaleOrderHandler : IRequestHandler<CreateSaleOrderCommand, CreateSaleOrderResult>
{
    private readonly IMapper _mapper;
    private readonly ISaleOrderRepository _orderRepository;
    private readonly ILogger<CreateSaleOrderHandler> _logger;

    public CreateSaleOrderHandler(ISaleOrderRepository orderRepository, IMapper mapper, ILogger<CreateSaleOrderHandler> logger)
    {
        _mapper = mapper;
        _orderRepository = orderRepository;
        _logger = logger;
    }

    /// <summary>
    /// Handles the CreateSaleOrderCommand request
    /// </summary>
    /// <param name="command">The CreateSaleOrder command</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>The created sale order details</returns>
    public async Task<CreateSaleOrderResult> Handle(CreateSaleOrderCommand command, CancellationToken cancellationToken)
    {
        var validator = new CreateSaleOrderValidator();
        var validationResult = await validator.ValidateAsync(command, cancellationToken);

        if (!validationResult.IsValid)
        {
            throw new ValidationException(validationResult.Errors);
        }

        var order = _mapper.Map<SaleOrder>(command);
        // Deprecated: OrderNumber is now generated by database sequence/default.
        // int nextOrderNumber = await _orderRepository.GetLastOrderNumber(cancellationToken) + 1;
        // order.OrderNumber = nextOrderNumber;
        order.ApplyDiscountAndCalcTotal();
        var createdOrder = await _orderRepository.CreateAsync(order, cancellationToken);

        var saleCreatedEvent = new SaleCreatedEvent(createdOrder.Id, createdOrder.OrderNumber);
        _logger.LogInformation("DomainEvent {EventType} {@Event}", nameof(SaleCreatedEvent), saleCreatedEvent);
        
        var result = _mapper.Map<CreateSaleOrderResult>(createdOrder);
        return result;
    }
}
